-- Etapa física: criando tabelas reais no PostgreSQL
CREATE TABLE EMPREGADOS (CODIGO INT, NOME VARCHAR(100), EMAIL TEXT);
CREATE TABLE DEPTOS (CODIGO INT, NOME VARCHAR(100));
CREATE TABLE CARGOS (CODIGO INT, NOME TEXT, SALARIO NUMERIC(7, 2));
CREATE TABLE PROJETOS (CODIGO INT, NOME VARCHAR(150), ORCAMENTO NUMERIC(10,2));

-- Inserindo dados reais
INSERT INTO EMPREGADOS VALUES (1, 'PAULO JOSÉ', 'PAULO@UNICSUL.BR');
INSERT INTO PROJETOS VALUES(1, 'ZenixCORE', 5000000.00);

-- Fazendo aparecer
SELECT * FROM PROJETOS;